# Example: How to use the reusable AI Code Review workflow
# Copy this file to your project's .github/workflows/ directory

name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  ai-review:
    # Replace 'your-org/CodeReview' with your actual repository path
    uses: your-org/CodeReview/.github/workflows/ai-code-review.yml@main
    secrets:
      AI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    # All inputs are optional, below are the defaults
    with:
      ai-provider: 'gemini'           # Options: gemini, openai, claude
      ai-model: ''                    # Empty for provider default
      min-score: 7
      max-files: 20
      max-lines: 500
      auto-merge: true
      merge-method: 'squash'
      language: 'zh'
      run-security-scan: true
      exclude-patterns: '*.md,*.txt,*.json,*.lock,*.yaml,*.yml'
      custom-prompt: ''               # Add project-specific review instructions
